FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ARG IBM_CLOUD_VERSION=2.1.1
ARG ARCH=amd64
ARG TERRAFORM_VERSION=terraform-0.13.7-1.x86_64

LABEL maintaner="Rafael Peria de Sene - rpsene@br.ibm.com "
LABEL tf_version="$TERRAFORM"
LABEL ibmcloud_version="$IBMCLOUD_VERSION"

COPY /files/x86_64.sh  /root/x86_64.sh

RUN chmod +x /root/x86_64.sh; /root/x86_64.sh